### ISSUE TITLE
name-service/v1/players return no Player ID

### ISSUE THREAD

**Issue by Teo230** [RumbleMike/ValorantAPI#1]
Hi,
I am trying to develop a Player Tracker. I created succefully the Auth Flow, so I can retrieve all I need to make request.
Now I am trying to retrieve the Player Id using EU endpoint, but seems not working. When I execute the request, I receive the current response

`{"DisplayName":"","Subject":"","GameName":"","TagLine":""}`

I don't know if I need some kind of permission or it's a wrong request, but the server responses me with empty parameters so I think it works with headers,body,... that I pass

Also I tried from Postman
![image](https://user-images.githubusercontent.com/34417048/90398804-4b3b8a00-e09a-11ea-8918-35a275accc67.png)

**Comment by Sprayxe** [comment]
I had the same problem so i used a different method.
My way:
url: `https://auth.riotgames.com/userinfo`
method: `POST`
authorization: `Bearer <your-token>`
headers: (Should work without the entitlements token, just try out)
body/payload: `{}`

The response will have a property called `sub`, which is the account id

If you're on JS, you can also just use my [library](https://www.npmjs.com/package/valorant.js)

**Comment by Teo230** [comment]
@Sprayxe no, I am using C# to develop a WPF application. I contacted @RumbleMike about this problem, seems a problem from Riot (the response is 503 - Service Unavailable), but he is investigating on it.
One more thing, you are using `https://auth.riotgames.com/userinfo`, this a part of the Auth Flow, this is not the endpoint used by Valorant Request API, so my problem is not related with yours, but it also a way to retrieve the Player ID, but this not resolve the main problem I think

**Comment by Sprayxe** [comment]
I had the same problem with the `name-service` endpoint as you have, so thats why i switched to the auth one

**Comment by Teo230** [comment]
I tryed with `auth` to retrieve Player ID, and now seems that the others request works fine. I use it until the problem will solve
