### ISSUE TITLE
how do I get the date of the last match?

### ISSUE THREAD

**Issue by west-28** [RumbleMike/ValorantAPI#6]
hi tell me how to decipher it?

"GameStartTime": 1593051973449,

how do I get the date of the last match?

**Comment by woolfi20** [comment]
Hello check this website [currentmillis](https://currentmillis.com/) 
![image](https://user-images.githubusercontent.com/74566790/100125269-a517d100-2e8d-11eb-9f94-7ab79c7a6819.png)

**Comment by west-28** [comment]
thanks
