### ISSUE TITLE
I'm dumb

### ISSUE THREAD

**Issue by walidashi** [RumbleMike/ValorantAPI#8]
Hey i'm not a pro but trying to when entering the access token and the X-Riot-Entitlements-JWT one and click send I get ``X-Riot-Entitlements-JWT`` what should I do?

**Comment by BobbyESP** [comment]
wHAt?

**Comment by walidashi** [comment]
![Opera Snapshot_2020-12-27_174053_web postman co](https://user-images.githubusercontent.com/67015071/103174421-ad877100-486a-11eb-919b-3b3bd69f24be.png)

**Comment by BobbyESP** [comment]
Download Postman for Desktop. It's the best option. Sometimes the browser blocks the requests

**Comment by yagizdo** [comment]
I did not understand exactly how to get Jwt. How did you get it?

It also requires jwt to get auth tokens. I couldn't quite understand the jwt part :/
